CREATE TABLE IF NOT EXISTS orders(
	orderId UUID PRIMARY KEY,
	dateCreated TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	dateEdited TIMESTAMP WITHOUT TIME ZONE,
	tableNumber INT NOT NULL,
	isOpen BOOLEAN NOT NULL,
	paymentMethod VARCHAR(20),
	datePaid TIMESTAMP WITHOUT TIME ZONE,
	totalAmount DECIMAL(20,2)
);

CREATE TABLE IF NOT EXISTS meals(
	name VARCHAR(50) PRIMARY KEY,
	description VARCHAR(300),
	price DECIMAL(20,2) NOT NULL,
	tax INT NOT NULL,
	dateCreated TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	dateEdited TIMESTAMP WITHOUT TIME ZONE,
	deprecated BOOLEAN,
	containsMeat BOOLEAN NOT NULL,
	foodType VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS drinks(
	name VARCHAR(50) PRIMARY KEY,
	description VARCHAR(300),
	price DECIMAL(20,2) NOT NULL,
	tax INT NOT NULL,
	dateCreated TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	dateEdited TIMESTAMP WITHOUT TIME ZONE,
	deprecated BOOLEAN,
	containsAlcohol BOOLEAN NOT NULL,
	beverageType VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS tax(
	taxId UUID PRIMARY KEY,
	taxRate INT NOT NULL,
	taxTotal DECIMAL(20,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS orderfood(
	orderId UUID NOT NULL,
	name VARCHAR(300) NOT NULL,
	amountOrdered INT NOT NULL,
	FOREIGN KEY (orderId) REFERENCES orders(orderId),
	FOREIGN KEY (name) REFERENCES meals(name),
	UNIQUE (orderId, name)
);

CREATE TABLE IF NOT EXISTS orderbeverage(
	orderId UUID NOT NULL,
	name VARCHAR(300) NOT NULL,
	amountOrdered INT NOT NULL,
	FOREIGN KEY (orderId) REFERENCES orders(orderId),
	FOREIGN KEY (name) REFERENCES drinks(name),
	UNIQUE (orderId, name)
);

CREATE TABLE IF NOT EXISTS ordertax(
	orderId UUID NOT NULL,
	taxId UUID NOT NULL,
	FOREIGN KEY (orderId) REFERENCES orders(orderId),
	FOREIGN KEY (taxId) REFERENCES tax(taxId),
	UNIQUE (orderId, taxId)
);